export { default as Home } from "./home/HomeLayout"
export { default as AllItems } from "./allItems/AllItemsBody"
export { default as Dresses } from "./dresses/DressesLayout"
export { default as Seasonal } from "./seasonal/SeasonalLayout"
export { default as Denims } from "./denims/DenimsLayout"
export { default as Tshirts } from "./tshirts/TshirtsLayout"
export { default as Top } from "./top/TopLayout"
export { default as Cart } from "./cart/CartLayout"
export { default as Detail } from './productDetail/ProductDetailBody'
